services:
  frontend:
    build: frontend
    expose:
      - "8000:8000"
  caddy:
    image: caddy:2.8.4-alpine
    restart: unless-stopped
    command: caddy reverse-proxy --from https://192.168.1.172:443 --to http://frontend:8000
    ports:
      - "80:80"
      - "443:443"
