version: '3'

services:
  backend:
    build: backend 
    expose:
      - "8080:8080"
  frontend:
    build: frontend
    expose:
      - "8000:8000"
    links:
      - backend
  caddy:
    image: caddy:2.8.4-alpine
    restart: unless-stopped
    volumes:
      - $PWD/caddy/Caddyfile:/etc/caddy/Caddyfile
    ports:
      - "80:80"
      - "443:443"