services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  backend:
    build: backend 
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_PASSWORD=e
      - POSTGRES_USER=postgres
      - PGUSER=postgres
      - POSTGRES_DB=db
      - FRONTEND_URL=$FRONTEND_URL
  frontend:
    build: 
      context: frontend
      args:
        - BACKEND_URL=$BACKEND_URL
    ports:
      - "3000:3000"
    depends_on:
      - backend
secrets:
  postgres_db:
    file: secrets/postgres_db.txt
  postgres_db_user:
    file: secrets/postgres_db_user.txt
  postgres_db_password:
    file: secrets/postgres_pass.txt