// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.6
// source: external_channel_manager/external-channel-manager.proto

package external_channel_manager

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateChannelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Public        bool                   `protobuf:"varint,1,opt,name=public,proto3" json:"public,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChannelRequest) Reset() {
	*x = CreateChannelRequest{}
	mi := &file_external_channel_manager_external_channel_manager_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChannelRequest) ProtoMessage() {}

func (x *CreateChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_external_channel_manager_external_channel_manager_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChannelRequest.ProtoReflect.Descriptor instead.
func (*CreateChannelRequest) Descriptor() ([]byte, []int) {
	return file_external_channel_manager_external_channel_manager_proto_rawDescGZIP(), []int{0}
}

func (x *CreateChannelRequest) GetPublic() bool {
	if x != nil {
		return x.Public
	}
	return false
}

func (x *CreateChannelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateChannelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     int64                  `protobuf:"varint,1,opt,name=channelId,proto3" json:"channelId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChannelResponse) Reset() {
	*x = CreateChannelResponse{}
	mi := &file_external_channel_manager_external_channel_manager_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChannelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChannelResponse) ProtoMessage() {}

func (x *CreateChannelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_external_channel_manager_external_channel_manager_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChannelResponse.ProtoReflect.Descriptor instead.
func (*CreateChannelResponse) Descriptor() ([]byte, []int) {
	return file_external_channel_manager_external_channel_manager_proto_rawDescGZIP(), []int{1}
}

func (x *CreateChannelResponse) GetChannelId() int64 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

type DeleteChannelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     int64                  `protobuf:"varint,1,opt,name=channelId,proto3" json:"channelId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChannelRequest) Reset() {
	*x = DeleteChannelRequest{}
	mi := &file_external_channel_manager_external_channel_manager_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChannelRequest) ProtoMessage() {}

func (x *DeleteChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_external_channel_manager_external_channel_manager_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChannelRequest.ProtoReflect.Descriptor instead.
func (*DeleteChannelRequest) Descriptor() ([]byte, []int) {
	return file_external_channel_manager_external_channel_manager_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteChannelRequest) GetChannelId() int64 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

type DeleteChannelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChannelResponse) Reset() {
	*x = DeleteChannelResponse{}
	mi := &file_external_channel_manager_external_channel_manager_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChannelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChannelResponse) ProtoMessage() {}

func (x *DeleteChannelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_external_channel_manager_external_channel_manager_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChannelResponse.ProtoReflect.Descriptor instead.
func (*DeleteChannelResponse) Descriptor() ([]byte, []int) {
	return file_external_channel_manager_external_channel_manager_proto_rawDescGZIP(), []int{3}
}

type ChangeChannelVisibilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     int64                  `protobuf:"varint,1,opt,name=channelId,proto3" json:"channelId,omitempty"`
	Public        bool                   `protobuf:"varint,2,opt,name=public,proto3" json:"public,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeChannelVisibilityRequest) Reset() {
	*x = ChangeChannelVisibilityRequest{}
	mi := &file_external_channel_manager_external_channel_manager_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeChannelVisibilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeChannelVisibilityRequest) ProtoMessage() {}

func (x *ChangeChannelVisibilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_external_channel_manager_external_channel_manager_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeChannelVisibilityRequest.ProtoReflect.Descriptor instead.
func (*ChangeChannelVisibilityRequest) Descriptor() ([]byte, []int) {
	return file_external_channel_manager_external_channel_manager_proto_rawDescGZIP(), []int{4}
}

func (x *ChangeChannelVisibilityRequest) GetChannelId() int64 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *ChangeChannelVisibilityRequest) GetPublic() bool {
	if x != nil {
		return x.Public
	}
	return false
}

type ChangeChannelVisibilityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeChannelVisibilityResponse) Reset() {
	*x = ChangeChannelVisibilityResponse{}
	mi := &file_external_channel_manager_external_channel_manager_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeChannelVisibilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeChannelVisibilityResponse) ProtoMessage() {}

func (x *ChangeChannelVisibilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_external_channel_manager_external_channel_manager_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeChannelVisibilityResponse.ProtoReflect.Descriptor instead.
func (*ChangeChannelVisibilityResponse) Descriptor() ([]byte, []int) {
	return file_external_channel_manager_external_channel_manager_proto_rawDescGZIP(), []int{5}
}

type JoinChannelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     int64                  `protobuf:"varint,1,opt,name=channelId,proto3" json:"channelId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinChannelRequest) Reset() {
	*x = JoinChannelRequest{}
	mi := &file_external_channel_manager_external_channel_manager_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinChannelRequest) ProtoMessage() {}

func (x *JoinChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_external_channel_manager_external_channel_manager_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinChannelRequest.ProtoReflect.Descriptor instead.
func (*JoinChannelRequest) Descriptor() ([]byte, []int) {
	return file_external_channel_manager_external_channel_manager_proto_rawDescGZIP(), []int{6}
}

func (x *JoinChannelRequest) GetChannelId() int64 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

type JoinChannelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinChannelResponse) Reset() {
	*x = JoinChannelResponse{}
	mi := &file_external_channel_manager_external_channel_manager_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinChannelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinChannelResponse) ProtoMessage() {}

func (x *JoinChannelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_external_channel_manager_external_channel_manager_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinChannelResponse.ProtoReflect.Descriptor instead.
func (*JoinChannelResponse) Descriptor() ([]byte, []int) {
	return file_external_channel_manager_external_channel_manager_proto_rawDescGZIP(), []int{7}
}

type AddToChannelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     int64                  `protobuf:"varint,1,opt,name=channelId,proto3" json:"channelId,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddToChannelRequest) Reset() {
	*x = AddToChannelRequest{}
	mi := &file_external_channel_manager_external_channel_manager_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddToChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToChannelRequest) ProtoMessage() {}

func (x *AddToChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_external_channel_manager_external_channel_manager_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToChannelRequest.ProtoReflect.Descriptor instead.
func (*AddToChannelRequest) Descriptor() ([]byte, []int) {
	return file_external_channel_manager_external_channel_manager_proto_rawDescGZIP(), []int{8}
}

func (x *AddToChannelRequest) GetChannelId() int64 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *AddToChannelRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type AddToChannelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddToChannelResponse) Reset() {
	*x = AddToChannelResponse{}
	mi := &file_external_channel_manager_external_channel_manager_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddToChannelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToChannelResponse) ProtoMessage() {}

func (x *AddToChannelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_external_channel_manager_external_channel_manager_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToChannelResponse.ProtoReflect.Descriptor instead.
func (*AddToChannelResponse) Descriptor() ([]byte, []int) {
	return file_external_channel_manager_external_channel_manager_proto_rawDescGZIP(), []int{9}
}

type GetChannelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PrefixSearch  string                 `protobuf:"bytes,1,opt,name=prefixSearch,proto3" json:"prefixSearch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChannelsRequest) Reset() {
	*x = GetChannelsRequest{}
	mi := &file_external_channel_manager_external_channel_manager_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChannelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChannelsRequest) ProtoMessage() {}

func (x *GetChannelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_external_channel_manager_external_channel_manager_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChannelsRequest.ProtoReflect.Descriptor instead.
func (*GetChannelsRequest) Descriptor() ([]byte, []int) {
	return file_external_channel_manager_external_channel_manager_proto_rawDescGZIP(), []int{10}
}

func (x *GetChannelsRequest) GetPrefixSearch() string {
	if x != nil {
		return x.PrefixSearch
	}
	return ""
}

type GetChannelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     int64                  `protobuf:"varint,1,opt,name=channelId,proto3" json:"channelId,omitempty"`
	ChannelName   string                 `protobuf:"bytes,2,opt,name=channelName,proto3" json:"channelName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChannelsResponse) Reset() {
	*x = GetChannelsResponse{}
	mi := &file_external_channel_manager_external_channel_manager_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChannelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChannelsResponse) ProtoMessage() {}

func (x *GetChannelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_external_channel_manager_external_channel_manager_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChannelsResponse.ProtoReflect.Descriptor instead.
func (*GetChannelsResponse) Descriptor() ([]byte, []int) {
	return file_external_channel_manager_external_channel_manager_proto_rawDescGZIP(), []int{11}
}

func (x *GetChannelsResponse) GetChannelId() int64 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *GetChannelsResponse) GetChannelName() string {
	if x != nil {
		return x.ChannelName
	}
	return ""
}

type GetAllChannelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllChannelsRequest) Reset() {
	*x = GetAllChannelsRequest{}
	mi := &file_external_channel_manager_external_channel_manager_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllChannelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllChannelsRequest) ProtoMessage() {}

func (x *GetAllChannelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_external_channel_manager_external_channel_manager_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllChannelsRequest.ProtoReflect.Descriptor instead.
func (*GetAllChannelsRequest) Descriptor() ([]byte, []int) {
	return file_external_channel_manager_external_channel_manager_proto_rawDescGZIP(), []int{12}
}

type GetAllChannelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     int64                  `protobuf:"varint,1,opt,name=channelId,proto3" json:"channelId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllChannelsResponse) Reset() {
	*x = GetAllChannelsResponse{}
	mi := &file_external_channel_manager_external_channel_manager_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllChannelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllChannelsResponse) ProtoMessage() {}

func (x *GetAllChannelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_external_channel_manager_external_channel_manager_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllChannelsResponse.ProtoReflect.Descriptor instead.
func (*GetAllChannelsResponse) Descriptor() ([]byte, []int) {
	return file_external_channel_manager_external_channel_manager_proto_rawDescGZIP(), []int{13}
}

func (x *GetAllChannelsResponse) GetChannelId() int64 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

type CanWatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     int64                  `protobuf:"varint,1,opt,name=channelId,proto3" json:"channelId,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CanWatchRequest) Reset() {
	*x = CanWatchRequest{}
	mi := &file_external_channel_manager_external_channel_manager_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CanWatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanWatchRequest) ProtoMessage() {}

func (x *CanWatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_external_channel_manager_external_channel_manager_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanWatchRequest.ProtoReflect.Descriptor instead.
func (*CanWatchRequest) Descriptor() ([]byte, []int) {
	return file_external_channel_manager_external_channel_manager_proto_rawDescGZIP(), []int{14}
}

func (x *CanWatchRequest) GetChannelId() int64 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *CanWatchRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CanWatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CanWatchResponse) Reset() {
	*x = CanWatchResponse{}
	mi := &file_external_channel_manager_external_channel_manager_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CanWatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanWatchResponse) ProtoMessage() {}

func (x *CanWatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_external_channel_manager_external_channel_manager_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanWatchResponse.ProtoReflect.Descriptor instead.
func (*CanWatchResponse) Descriptor() ([]byte, []int) {
	return file_external_channel_manager_external_channel_manager_proto_rawDescGZIP(), []int{15}
}

type CanWriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     int64                  `protobuf:"varint,1,opt,name=channelId,proto3" json:"channelId,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CanWriteRequest) Reset() {
	*x = CanWriteRequest{}
	mi := &file_external_channel_manager_external_channel_manager_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CanWriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanWriteRequest) ProtoMessage() {}

func (x *CanWriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_external_channel_manager_external_channel_manager_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanWriteRequest.ProtoReflect.Descriptor instead.
func (*CanWriteRequest) Descriptor() ([]byte, []int) {
	return file_external_channel_manager_external_channel_manager_proto_rawDescGZIP(), []int{16}
}

func (x *CanWriteRequest) GetChannelId() int64 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *CanWriteRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CanWriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CanWriteResponse) Reset() {
	*x = CanWriteResponse{}
	mi := &file_external_channel_manager_external_channel_manager_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CanWriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanWriteResponse) ProtoMessage() {}

func (x *CanWriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_external_channel_manager_external_channel_manager_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanWriteResponse.ProtoReflect.Descriptor instead.
func (*CanWriteResponse) Descriptor() ([]byte, []int) {
	return file_external_channel_manager_external_channel_manager_proto_rawDescGZIP(), []int{17}
}

var File_external_channel_manager_external_channel_manager_proto protoreflect.FileDescriptor

const file_external_channel_manager_external_channel_manager_proto_rawDesc = "" +
	"\n" +
	"7external_channel_manager/external-channel-manager.proto\x12\x18external_channel_manager\"B\n" +
	"\x14CreateChannelRequest\x12\x16\n" +
	"\x06public\x18\x01 \x01(\bR\x06public\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"5\n" +
	"\x15CreateChannelResponse\x12\x1c\n" +
	"\tchannelId\x18\x01 \x01(\x03R\tchannelId\"4\n" +
	"\x14DeleteChannelRequest\x12\x1c\n" +
	"\tchannelId\x18\x01 \x01(\x03R\tchannelId\"\x17\n" +
	"\x15DeleteChannelResponse\"V\n" +
	"\x1eChangeChannelVisibilityRequest\x12\x1c\n" +
	"\tchannelId\x18\x01 \x01(\x03R\tchannelId\x12\x16\n" +
	"\x06public\x18\x02 \x01(\bR\x06public\"!\n" +
	"\x1fChangeChannelVisibilityResponse\"2\n" +
	"\x12JoinChannelRequest\x12\x1c\n" +
	"\tchannelId\x18\x01 \x01(\x03R\tchannelId\"\x15\n" +
	"\x13JoinChannelResponse\"K\n" +
	"\x13AddToChannelRequest\x12\x1c\n" +
	"\tchannelId\x18\x01 \x01(\x03R\tchannelId\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x03R\x06userId\"\x16\n" +
	"\x14AddToChannelResponse\"8\n" +
	"\x12GetChannelsRequest\x12\"\n" +
	"\fprefixSearch\x18\x01 \x01(\tR\fprefixSearch\"U\n" +
	"\x13GetChannelsResponse\x12\x1c\n" +
	"\tchannelId\x18\x01 \x01(\x03R\tchannelId\x12 \n" +
	"\vchannelName\x18\x02 \x01(\tR\vchannelName\"\x17\n" +
	"\x15GetAllChannelsRequest\"6\n" +
	"\x16GetAllChannelsResponse\x12\x1c\n" +
	"\tchannelId\x18\x01 \x01(\x03R\tchannelId\"G\n" +
	"\x0fCanWatchRequest\x12\x1c\n" +
	"\tchannelId\x18\x01 \x01(\x03R\tchannelId\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x03R\x06userId\"\x12\n" +
	"\x10CanWatchResponse\"G\n" +
	"\x0fCanWriteRequest\x12\x1c\n" +
	"\tchannelId\x18\x01 \x01(\x03R\tchannelId\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x03R\x06userId\"\x12\n" +
	"\x10CanWriteResponse2\xa5\b\n" +
	"\x16externalchannelmanager\x12r\n" +
	"\rCreateChannel\x12..external_channel_manager.CreateChannelRequest\x1a/.external_channel_manager.CreateChannelResponse\"\x00\x12r\n" +
	"\rDeleteChannel\x12..external_channel_manager.DeleteChannelRequest\x1a/.external_channel_manager.DeleteChannelResponse\"\x00\x12\x90\x01\n" +
	"\x17ChangeChannelVisibility\x128.external_channel_manager.ChangeChannelVisibilityRequest\x1a9.external_channel_manager.ChangeChannelVisibilityResponse\"\x00\x12l\n" +
	"\vJoinChannel\x12,.external_channel_manager.JoinChannelRequest\x1a-.external_channel_manager.JoinChannelResponse\"\x00\x12o\n" +
	"\fAddToChannel\x12-.external_channel_manager.AddToChannelRequest\x1a..external_channel_manager.AddToChannelResponse\"\x00\x12n\n" +
	"\vGetChannels\x12,.external_channel_manager.GetChannelsRequest\x1a-.external_channel_manager.GetChannelsResponse\"\x000\x01\x12w\n" +
	"\x0eGetAllChannels\x12/.external_channel_manager.GetAllChannelsRequest\x1a0.external_channel_manager.GetAllChannelsResponse\"\x000\x01\x12c\n" +
	"\bCanWatch\x12).external_channel_manager.CanWatchRequest\x1a*.external_channel_manager.CanWatchResponse\"\x00\x12c\n" +
	"\bCanWrite\x12).external_channel_manager.CanWriteRequest\x1a*.external_channel_manager.CanWriteResponse\"\x00BNZLgithub.com/WadeCappa/real_time_chat/channel-manager/external-channel-managerb\x06proto3"

var (
	file_external_channel_manager_external_channel_manager_proto_rawDescOnce sync.Once
	file_external_channel_manager_external_channel_manager_proto_rawDescData []byte
)

func file_external_channel_manager_external_channel_manager_proto_rawDescGZIP() []byte {
	file_external_channel_manager_external_channel_manager_proto_rawDescOnce.Do(func() {
		file_external_channel_manager_external_channel_manager_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_external_channel_manager_external_channel_manager_proto_rawDesc), len(file_external_channel_manager_external_channel_manager_proto_rawDesc)))
	})
	return file_external_channel_manager_external_channel_manager_proto_rawDescData
}

var file_external_channel_manager_external_channel_manager_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_external_channel_manager_external_channel_manager_proto_goTypes = []any{
	(*CreateChannelRequest)(nil),            // 0: external_channel_manager.CreateChannelRequest
	(*CreateChannelResponse)(nil),           // 1: external_channel_manager.CreateChannelResponse
	(*DeleteChannelRequest)(nil),            // 2: external_channel_manager.DeleteChannelRequest
	(*DeleteChannelResponse)(nil),           // 3: external_channel_manager.DeleteChannelResponse
	(*ChangeChannelVisibilityRequest)(nil),  // 4: external_channel_manager.ChangeChannelVisibilityRequest
	(*ChangeChannelVisibilityResponse)(nil), // 5: external_channel_manager.ChangeChannelVisibilityResponse
	(*JoinChannelRequest)(nil),              // 6: external_channel_manager.JoinChannelRequest
	(*JoinChannelResponse)(nil),             // 7: external_channel_manager.JoinChannelResponse
	(*AddToChannelRequest)(nil),             // 8: external_channel_manager.AddToChannelRequest
	(*AddToChannelResponse)(nil),            // 9: external_channel_manager.AddToChannelResponse
	(*GetChannelsRequest)(nil),              // 10: external_channel_manager.GetChannelsRequest
	(*GetChannelsResponse)(nil),             // 11: external_channel_manager.GetChannelsResponse
	(*GetAllChannelsRequest)(nil),           // 12: external_channel_manager.GetAllChannelsRequest
	(*GetAllChannelsResponse)(nil),          // 13: external_channel_manager.GetAllChannelsResponse
	(*CanWatchRequest)(nil),                 // 14: external_channel_manager.CanWatchRequest
	(*CanWatchResponse)(nil),                // 15: external_channel_manager.CanWatchResponse
	(*CanWriteRequest)(nil),                 // 16: external_channel_manager.CanWriteRequest
	(*CanWriteResponse)(nil),                // 17: external_channel_manager.CanWriteResponse
}
var file_external_channel_manager_external_channel_manager_proto_depIdxs = []int32{
	0,  // 0: external_channel_manager.externalchannelmanager.CreateChannel:input_type -> external_channel_manager.CreateChannelRequest
	2,  // 1: external_channel_manager.externalchannelmanager.DeleteChannel:input_type -> external_channel_manager.DeleteChannelRequest
	4,  // 2: external_channel_manager.externalchannelmanager.ChangeChannelVisibility:input_type -> external_channel_manager.ChangeChannelVisibilityRequest
	6,  // 3: external_channel_manager.externalchannelmanager.JoinChannel:input_type -> external_channel_manager.JoinChannelRequest
	8,  // 4: external_channel_manager.externalchannelmanager.AddToChannel:input_type -> external_channel_manager.AddToChannelRequest
	10, // 5: external_channel_manager.externalchannelmanager.GetChannels:input_type -> external_channel_manager.GetChannelsRequest
	12, // 6: external_channel_manager.externalchannelmanager.GetAllChannels:input_type -> external_channel_manager.GetAllChannelsRequest
	14, // 7: external_channel_manager.externalchannelmanager.CanWatch:input_type -> external_channel_manager.CanWatchRequest
	16, // 8: external_channel_manager.externalchannelmanager.CanWrite:input_type -> external_channel_manager.CanWriteRequest
	1,  // 9: external_channel_manager.externalchannelmanager.CreateChannel:output_type -> external_channel_manager.CreateChannelResponse
	3,  // 10: external_channel_manager.externalchannelmanager.DeleteChannel:output_type -> external_channel_manager.DeleteChannelResponse
	5,  // 11: external_channel_manager.externalchannelmanager.ChangeChannelVisibility:output_type -> external_channel_manager.ChangeChannelVisibilityResponse
	7,  // 12: external_channel_manager.externalchannelmanager.JoinChannel:output_type -> external_channel_manager.JoinChannelResponse
	9,  // 13: external_channel_manager.externalchannelmanager.AddToChannel:output_type -> external_channel_manager.AddToChannelResponse
	11, // 14: external_channel_manager.externalchannelmanager.GetChannels:output_type -> external_channel_manager.GetChannelsResponse
	13, // 15: external_channel_manager.externalchannelmanager.GetAllChannels:output_type -> external_channel_manager.GetAllChannelsResponse
	15, // 16: external_channel_manager.externalchannelmanager.CanWatch:output_type -> external_channel_manager.CanWatchResponse
	17, // 17: external_channel_manager.externalchannelmanager.CanWrite:output_type -> external_channel_manager.CanWriteResponse
	9,  // [9:18] is the sub-list for method output_type
	0,  // [0:9] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_external_channel_manager_external_channel_manager_proto_init() }
func file_external_channel_manager_external_channel_manager_proto_init() {
	if File_external_channel_manager_external_channel_manager_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_external_channel_manager_external_channel_manager_proto_rawDesc), len(file_external_channel_manager_external_channel_manager_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_external_channel_manager_external_channel_manager_proto_goTypes,
		DependencyIndexes: file_external_channel_manager_external_channel_manager_proto_depIdxs,
		MessageInfos:      file_external_channel_manager_external_channel_manager_proto_msgTypes,
	}.Build()
	File_external_channel_manager_external_channel_manager_proto = out.File
	file_external_channel_manager_external_channel_manager_proto_goTypes = nil
	file_external_channel_manager_external_channel_manager_proto_depIdxs = nil
}
