/**
 * @fileoverview gRPC-Web generated client stub for chat_db
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.19.6
// source: chat-db.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as chat$db_pb from './chat-db_pb'; // proto import: "chat-db.proto"


export class chatdbClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'binary';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorReadMostRecent = new grpcWeb.MethodDescriptor(
    '/chat_db.chatdb/ReadMostRecent',
    grpcWeb.MethodType.SERVER_STREAMING,
    chat$db_pb.ReadMostRecentRequest,
    chat$db_pb.ReadMostRecentResponse,
    (request: chat$db_pb.ReadMostRecentRequest) => {
      return request.serializeBinary();
    },
    chat$db_pb.ReadMostRecentResponse.deserializeBinary
  );

  readMostRecent(
    request: chat$db_pb.ReadMostRecentRequest,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<chat$db_pb.ReadMostRecentResponse> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/chat_db.chatdb/ReadMostRecent',
      request,
      metadata || {},
      this.methodDescriptorReadMostRecent);
  }

  methodDescriptorPublishMessage = new grpcWeb.MethodDescriptor(
    '/chat_db.chatdb/PublishMessage',
    grpcWeb.MethodType.UNARY,
    chat$db_pb.PublishMessageRequest,
    chat$db_pb.PublishMessageResponse,
    (request: chat$db_pb.PublishMessageRequest) => {
      return request.serializeBinary();
    },
    chat$db_pb.PublishMessageResponse.deserializeBinary
  );

  publishMessage(
    request: chat$db_pb.PublishMessageRequest,
    metadata?: grpcWeb.Metadata | null): Promise<chat$db_pb.PublishMessageResponse>;

  publishMessage(
    request: chat$db_pb.PublishMessageRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: chat$db_pb.PublishMessageResponse) => void): grpcWeb.ClientReadableStream<chat$db_pb.PublishMessageResponse>;

  publishMessage(
    request: chat$db_pb.PublishMessageRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: chat$db_pb.PublishMessageResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/chat_db.chatdb/PublishMessage',
        request,
        metadata || {},
        this.methodDescriptorPublishMessage,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/chat_db.chatdb/PublishMessage',
    request,
    metadata || {},
    this.methodDescriptorPublishMessage);
  }

}

