// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.6
// source: chat-writer/chat-writer.proto

package chat_writer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PublishMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishMessageResponse) Reset() {
	*x = PublishMessageResponse{}
	mi := &file_chat_writer_chat_writer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishMessageResponse) ProtoMessage() {}

func (x *PublishMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_writer_chat_writer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishMessageResponse.ProtoReflect.Descriptor instead.
func (*PublishMessageResponse) Descriptor() ([]byte, []int) {
	return file_chat_writer_chat_writer_proto_rawDescGZIP(), []int{0}
}

type PublishMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     int64                  `protobuf:"varint,1,opt,name=channelId,proto3" json:"channelId,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishMessageRequest) Reset() {
	*x = PublishMessageRequest{}
	mi := &file_chat_writer_chat_writer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishMessageRequest) ProtoMessage() {}

func (x *PublishMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_writer_chat_writer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishMessageRequest.ProtoReflect.Descriptor instead.
func (*PublishMessageRequest) Descriptor() ([]byte, []int) {
	return file_chat_writer_chat_writer_proto_rawDescGZIP(), []int{1}
}

func (x *PublishMessageRequest) GetChannelId() int64 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *PublishMessageRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_chat_writer_chat_writer_proto protoreflect.FileDescriptor

const file_chat_writer_chat_writer_proto_rawDesc = "" +
	"\n" +
	"\x1dchat-writer/chat-writer.proto\x12\vchat_writer\"\x18\n" +
	"\x16PublishMessageResponse\"O\n" +
	"\x15PublishMessageRequest\x12\x1c\n" +
	"\tchannelId\x18\x01 \x01(\x03R\tchannelId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2o\n" +
	"\x10chatwriterserver\x12[\n" +
	"\x0ePublishMessage\x12\".chat_writer.PublishMessageRequest\x1a#.chat_writer.PublishMessageResponse\"\x00B=Z;github.com/WadeCappa/real_time_chat/chat-writer/chat-writerb\x06proto3"

var (
	file_chat_writer_chat_writer_proto_rawDescOnce sync.Once
	file_chat_writer_chat_writer_proto_rawDescData []byte
)

func file_chat_writer_chat_writer_proto_rawDescGZIP() []byte {
	file_chat_writer_chat_writer_proto_rawDescOnce.Do(func() {
		file_chat_writer_chat_writer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chat_writer_chat_writer_proto_rawDesc), len(file_chat_writer_chat_writer_proto_rawDesc)))
	})
	return file_chat_writer_chat_writer_proto_rawDescData
}

var file_chat_writer_chat_writer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_chat_writer_chat_writer_proto_goTypes = []any{
	(*PublishMessageResponse)(nil), // 0: chat_writer.PublishMessageResponse
	(*PublishMessageRequest)(nil),  // 1: chat_writer.PublishMessageRequest
}
var file_chat_writer_chat_writer_proto_depIdxs = []int32{
	1, // 0: chat_writer.chatwriterserver.PublishMessage:input_type -> chat_writer.PublishMessageRequest
	0, // 1: chat_writer.chatwriterserver.PublishMessage:output_type -> chat_writer.PublishMessageResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_chat_writer_chat_writer_proto_init() }
func file_chat_writer_chat_writer_proto_init() {
	if File_chat_writer_chat_writer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chat_writer_chat_writer_proto_rawDesc), len(file_chat_writer_chat_writer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chat_writer_chat_writer_proto_goTypes,
		DependencyIndexes: file_chat_writer_chat_writer_proto_depIdxs,
		MessageInfos:      file_chat_writer_chat_writer_proto_msgTypes,
	}.Build()
	File_chat_writer_chat_writer_proto = out.File
	file_chat_writer_chat_writer_proto_goTypes = nil
	file_chat_writer_chat_writer_proto_depIdxs = nil
}
