// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.6
// source: chat-writer/chat-writer.proto

package chat_writer

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Chatwriterserver_PublishMessage_FullMethodName = "/chat_writer.chatwriterserver/PublishMessage"
)

// ChatwriterserverClient is the client API for Chatwriterserver service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChatwriterserverClient interface {
	PublishMessage(ctx context.Context, in *PublishMessageRequest, opts ...grpc.CallOption) (*PublishMessageResponse, error)
}

type chatwriterserverClient struct {
	cc grpc.ClientConnInterface
}

func NewChatwriterserverClient(cc grpc.ClientConnInterface) ChatwriterserverClient {
	return &chatwriterserverClient{cc}
}

func (c *chatwriterserverClient) PublishMessage(ctx context.Context, in *PublishMessageRequest, opts ...grpc.CallOption) (*PublishMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishMessageResponse)
	err := c.cc.Invoke(ctx, Chatwriterserver_PublishMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatwriterserverServer is the server API for Chatwriterserver service.
// All implementations must embed UnimplementedChatwriterserverServer
// for forward compatibility.
type ChatwriterserverServer interface {
	PublishMessage(context.Context, *PublishMessageRequest) (*PublishMessageResponse, error)
	mustEmbedUnimplementedChatwriterserverServer()
}

// UnimplementedChatwriterserverServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChatwriterserverServer struct{}

func (UnimplementedChatwriterserverServer) PublishMessage(context.Context, *PublishMessageRequest) (*PublishMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishMessage not implemented")
}
func (UnimplementedChatwriterserverServer) mustEmbedUnimplementedChatwriterserverServer() {}
func (UnimplementedChatwriterserverServer) testEmbeddedByValue()                          {}

// UnsafeChatwriterserverServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChatwriterserverServer will
// result in compilation errors.
type UnsafeChatwriterserverServer interface {
	mustEmbedUnimplementedChatwriterserverServer()
}

func RegisterChatwriterserverServer(s grpc.ServiceRegistrar, srv ChatwriterserverServer) {
	// If the following call pancis, it indicates UnimplementedChatwriterserverServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Chatwriterserver_ServiceDesc, srv)
}

func _Chatwriterserver_PublishMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatwriterserverServer).PublishMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chatwriterserver_PublishMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatwriterserverServer).PublishMessage(ctx, req.(*PublishMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Chatwriterserver_ServiceDesc is the grpc.ServiceDesc for Chatwriterserver service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Chatwriterserver_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chat_writer.chatwriterserver",
	HandlerType: (*ChatwriterserverServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PublishMessage",
			Handler:    _Chatwriterserver_PublishMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chat-writer/chat-writer.proto",
}
